language: go

go:
  - 1.7.3

script:
  - if [ "${TRAVIS_TAG}" == "" ]; then
      export VERSION=`git rev-parse --abbrev-ref HEAD`;
    else
      export VERSION=${TRAVIS_TAG:1};
    fi;
    export BUILD=`git rev-parse HEAD`;
    echo ${VERSION} ${BUILD}
  - make build;
  - make test;
  - if [ "${VERSION}" != "HEAD" ]; then
      make dist;
    fi;

notifications:
  email: false
